[package]
name = "road-macros"
version = "0.1.0"
edition = "2021"
metadata.nix.build = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
road-types = { path = "../road-types" }
abi_stable = "0.11"
